config/routes.rb
Rails.application.routes.draw do



  resources :nota_trab
  resources :presencas
  resources :matriculas

  resources :notas
  resources :professores
  resources :alunos

  resources :trabalhos

  resources :cursos
  resources :aulas

  resources :usuarios

  resources :disciplinas

end

app/models/aluno.rb
class Aluno < ApplicationRecord
  belongs_to :usuario
  validates :usuario, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aula.rb
class Aula < ApplicationRecord
  belongs_to :disciplina

  validates :disciplina, :data, :objetivo, :realizado, presence:true

end

app/models/curso.rb
class Curso < ApplicationRecord

    validates :nome, presence: true

end

app/models/disciplina.rb
class Disciplina < ApplicationRecord
    validates :nome, :carga_horaria, presence:  true
end

app/models/matricula.rb
class Matricula < ApplicationRecord
  belongs_to :usuario
  belongs_to :curso

  
end

app/models/nota.rb
class Nota < ApplicationRecord
  belongs_to :aluno
  belongs_to :professor
  belongs_to :disciplina

 
end

app/models/nota_trab.rb
class NotaTrab < ApplicationRecord
  belongs_to :aluno
  belongs_to :professor
  belongs_to :disciplina
end

app/models/presenca.rb
class Presenca < ApplicationRecord
  belongs_to :curso
  belongs_to :aluno
  belongs_to :professor
end

app/models/professor.rb
class Professor < ApplicationRecord
  belongs_to :usuario
end

app/models/trabalho.rb
class Trabalho < ApplicationRecord
  belongs_to :disciplina
  validates :descricao, :disciplina, :data_de_entrega, presence: true

end

app/models/usuario.rb
class Usuario < ApplicationRecord

    validates :nome_aluno, :documento, :pai, :mae, :endereco, presence: true

end

app/controllers/presencas_controller.rb
class PresencasController < ApplicationController
  before_action :set_presenca, only: [:show, :edit, :update, :destroy]

  # GET /presencas
  # GET /presencas.json
  def index
    @presencas = Presenca.all
  end

  # GET /presencas/1
  # GET /presencas/1.json
  def show
  end

  # GET /presencas/new
  def new
    @presenca = Presenca.new
  end

  # GET /presencas/1/edit
  def edit
  end

  # POST /presencas
  # POST /presencas.json
  def create
    @presenca = Presenca.new(presenca_params)

    respond_to do |format|
      if @presenca.save
        format.html { redirect_to @presenca, notice: 'Presenca was successfully created.' }
        format.json { render :show, status: :created, location: @presenca }
      else
        format.html { render :new }
        format.json { render json: @presenca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presencas/1
  # PATCH/PUT /presencas/1.json
  def update
    respond_to do |format|
      if @presenca.update(presenca_params)
        format.html { redirect_to @presenca, notice: 'Presenca was successfully updated.' }
        format.json { render :show, status: :ok, location: @presenca }
      else
        format.html { render :edit }
        format.json { render json: @presenca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presencas/1
  # DELETE /presencas/1.json
  def destroy
    @presenca.destroy
    respond_to do |format|
      format.html { redirect_to presencas_url, notice: 'Presenca was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presenca
      @presenca = Presenca.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def presenca_params
      params.require(:presenca).permit(:disciplina, :belongs_to, :aluno, :belongs_to, :data, :curso_id)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aulas_helper.rb
module AulasHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/matriculas_helper.rb
module MatriculasHelper
end

app/helpers/nota_trab_helper.rb
module NotaTrabHelper
end

app/helpers/notas_helper.rb
module NotasHelper
end

app/helpers/presencas_helper.rb
module PresencasHelper
end

app/helpers/trabalhos_helper.rb
module TrabalhosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/presencas/_form.html.erb
<%= form_with(model: presenca, local: true) do |form| %>
  <% if presenca.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(presenca.errors.count, "error") %> prohibited this presenca from being saved:</h2>

      <ul>
      <% presenca.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :disciplina %>
    <%= form.text_field :disciplina %>
  </div>

  <div class="field">
    <%= form.label :belongs_to %>
    <%= form.text_field :belongs_to %>
  </div>

  <div class="field">
    <%= form.label :aluno %>
    <%= form.text_field :aluno %>
  </div>

  <div class="field">
    <%= form.label :belongs_to %>
    <%= form.text_field :belongs_to %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.date_select :data %>
  </div>

  <div class="field">
    <%= form.label :curso_id %>
    <%= form.text_field :curso_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/presencas/edit.html.erb
<h1>Editing Presenca</h1>

<%= render 'form', presenca: @presenca %>

<%= link_to 'Show', @presenca %> |
<%= link_to 'Back', presencas_path %>

app/views/presencas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Presencas</h1>

<table>
  <thead>
    <tr>
      <th>Disciplina</th>
      <th>Belongs to</th>
      <th>Aluno</th>
      <th>Belongs to</th>
      <th>Data</th>
      <th>Curso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @presencas.each do |presenca| %>
      <tr>
        <td><%= presenca.disciplina %></td>
        <td><%= presenca.belongs_to %></td>
        <td><%= presenca.aluno %></td>
        <td><%= presenca.belongs_to %></td>
        <td><%= presenca.data %></td>
        <td><%= presenca.curso %></td>
        <td><%= link_to 'Show', presenca %></td>
        <td><%= link_to 'Edit', edit_presenca_path(presenca) %></td>
        <td><%= link_to 'Destroy', presenca, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Presenca', new_presenca_path %>

app/views/presencas/new.html.erb
<h1>New Presenca</h1>

<%= render 'form', presenca: @presenca %>

<%= link_to 'Back', presencas_path %>

app/views/presencas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Disciplina:</strong>
  <%= @presenca.disciplina %>
</p>

<p>
  <strong>Belongs to:</strong>
  <%= @presenca.belongs_to %>
</p>

<p>
  <strong>Aluno:</strong>
  <%= @presenca.aluno %>
</p>

<p>
  <strong>Belongs to:</strong>
  <%= @presenca.belongs_to %>
</p>

<p>
  <strong>Data:</strong>
  <%= @presenca.data %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @presenca.curso %>
</p>

<%= link_to 'Edit', edit_presenca_path(@presenca) %> |
<%= link_to 'Back', presencas_path %>