config/routes.rb
Rails.application.routes.draw do



  resources :nota_trab
  resources :presencas
  resources :matriculas

  resources :notas
  resources :professores
  resources :alunos

  resources :trabalhos

  resources :cursos
  resources :aulas

  resources :usuarios

  resources :disciplinas

end

app/models/aluno.rb
class Aluno < ApplicationRecord
  belongs_to :usuario
  validates :usuario, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aula.rb
class Aula < ApplicationRecord
  belongs_to :disciplina

  validates :disciplina, :data, :objetivo, :realizado, presence:true

end

app/models/curso.rb
class Curso < ApplicationRecord

    validates :nome, presence: true

end

app/models/disciplina.rb
class Disciplina < ApplicationRecord
    validates :nome, :carga_horaria, presence:  true
end

app/models/matricula.rb
class Matricula < ApplicationRecord
  belongs_to :usuario
  belongs_to :curso

  
end

app/models/nota.rb
class Nota < ApplicationRecord
  belongs_to :aluno
  belongs_to :professor
  belongs_to :disciplina

 
end

app/models/nota_trab.rb
class NotaTrab < ApplicationRecord
  belongs_to :aluno
  belongs_to :professor
  belongs_to :disciplina
end

app/models/presenca.rb
class Presenca < ApplicationRecord
  belongs_to :curso
  belongs_to :aluno
  belongs_to :professor
end

app/models/professor.rb
class Professor < ApplicationRecord
  belongs_to :usuario
end

app/models/trabalho.rb
class Trabalho < ApplicationRecord
  belongs_to :disciplina
  validates :descricao, :disciplina, :data_de_entrega, presence: true

end

app/models/usuario.rb
class Usuario < ApplicationRecord

    validates :nome_aluno, :documento, :pai, :mae, :endereco, presence: true

end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]

  # GET /alunos
  # GET /alunos.json
  def index
    @alunos = Aluno.all
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: 'Aluno was successfully created.' }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: 'Aluno was successfully updated.' }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: 'Aluno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(:usuario_id)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aulas_helper.rb
module AulasHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/matriculas_helper.rb
module MatriculasHelper
end

app/helpers/nota_trab_helper.rb
module NotaTrabHelper
end

app/helpers/notas_helper.rb
module NotasHelper
end

app/helpers/presencas_helper.rb
module PresencasHelper
end

app/helpers/trabalhos_helper.rb
module TrabalhosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/alunos/_form.html.erb
<%= form_with(model: aluno, local: true) do |form| %>
  <% if aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
      <% aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :usuario_id %>
    <%= form.select(:usuario_id,
                    Usuario.all.collect{|cl|[cl.nome_aluno, cl.id]}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<h1>Editing Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Show', @aluno %> |
<%= link_to 'Back', alunos_path %>

app/views/alunos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alunos</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.usuario.nome_aluno %></td>
        <td><%= link_to 'Show', aluno %></td>
        <td><%= link_to 'Edit', edit_aluno_path(aluno) %></td>
        <td><%= link_to 'Destroy', aluno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aluno', new_aluno_path %>

app/views/alunos/new.html.erb
<h1>New Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Back', alunos_path %>

app/views/alunos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @aluno.usuario %>
</p>

<%= link_to 'Edit', edit_aluno_path(@aluno) %> |
<%= link_to 'Back', alunos_path %>