config/routes.rb
Rails.application.routes.draw do



  resources :nota_trab
  resources :presencas
  resources :matriculas

  resources :notas
  resources :professores
  resources :alunos

  resources :trabalhos

  resources :cursos
  resources :aulas

  resources :usuarios

  resources :disciplinas

end

app/models/aluno.rb
class Aluno < ApplicationRecord
  belongs_to :usuario
  validates :usuario, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aula.rb
class Aula < ApplicationRecord
  belongs_to :disciplina

  validates :disciplina, :data, :objetivo, :realizado, presence:true

end

app/models/curso.rb
class Curso < ApplicationRecord

    validates :nome, presence: true

end

app/models/disciplina.rb
class Disciplina < ApplicationRecord
    validates :nome, :carga_horaria, presence:  true
end

app/models/matricula.rb
class Matricula < ApplicationRecord
  belongs_to :usuario
  belongs_to :curso

  
end

app/models/nota.rb
class Nota < ApplicationRecord
  belongs_to :aluno
  belongs_to :professor
  belongs_to :disciplina

 
end

app/models/nota_trab.rb
class NotaTrab < ApplicationRecord
  belongs_to :aluno
  belongs_to :professor
  belongs_to :disciplina
end

app/models/presenca.rb
class Presenca < ApplicationRecord
  belongs_to :curso
  belongs_to :aluno
  belongs_to :professor
end

app/models/professor.rb
class Professor < ApplicationRecord
  belongs_to :usuario
end

app/models/trabalho.rb
class Trabalho < ApplicationRecord
  belongs_to :disciplina
  validates :descricao, :disciplina, :data_de_entrega, presence: true

end

app/models/usuario.rb
class Usuario < ApplicationRecord

    validates :nome_aluno, :documento, :pai, :mae, :endereco, presence: true

end

app/controllers/notas_controller.rb
class NotasController < ApplicationController
  before_action :set_nota, only: [:show, :edit, :update, :destroy]

  # GET /notas
  # GET /notas.json
  def index
    @notas = Nota.all
  end

  # GET /notas/1
  # GET /notas/1.json
  def show
  end

  # GET /notas/new
  def new
    @nota = Nota.new
  end

  # GET /notas/1/edit
  def edit
  end

  # POST /notas
  # POST /notas.json
  def create
    @nota = Nota.new(nota_params)

    respond_to do |format|
      if @nota.save
        format.html { redirect_to @nota, notice: 'Nota was successfully created.' }
        format.json { render :show, status: :created, location: @nota }
      else
        format.html { render :new }
        format.json { render json: @nota.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notas/1
  # PATCH/PUT /notas/1.json
  def update
    respond_to do |format|
      if @nota.update(nota_params)
        format.html { redirect_to @nota, notice: 'Nota was successfully updated.' }
        format.json { render :show, status: :ok, location: @nota }
      else
        format.html { render :edit }
        format.json { render json: @nota.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notas/1
  # DELETE /notas/1.json
  def destroy
    @nota.destroy
    respond_to do |format|
      format.html { redirect_to notas_url, notice: 'Nota was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nota
      @nota = Nota.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nota_params
      params.require(:nota).permit(:nota, :aluno_id, :professor_id, :disciplina_id)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aulas_helper.rb
module AulasHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/matriculas_helper.rb
module MatriculasHelper
end

app/helpers/nota_trab_helper.rb
module NotaTrabHelper
end

app/helpers/notas_helper.rb
module NotasHelper
end

app/helpers/presencas_helper.rb
module PresencasHelper
end

app/helpers/trabalhos_helper.rb
module TrabalhosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/notas/_form.html.erb
<%= form_with(model: nota, local: true) do |form| %>
  <% if nota.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nota.errors.count, "error") %> prohibited this nota from being saved:</h2>

      <ul>
      <% nota.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nota %>
    <%= form.text_field :nota %>
  </div>

  <div class="field">
    <%= form.label :aluno_id %>
    <%= form.select(:aluno_id,
                      Aluno.all.collect{|cl|[cl.usuario.nome_aluno, cl.id]}) %>
  </div>

  <div class="field">
    <%= form.label :professor_id %>
    <%= form.select(:professor_id,
    Professor.all.collect{|cl|[cl.usuario.nome_aluno, cl.id]}) %>
  </div>

  <div class="field">
    <%= form.label :disciplina_id %>
    <%= form.select :disciplina_id,
    Disciplina.all.collect{|cl|[cl.nome, cl.id]} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notas/edit.html.erb
<h1>Editing Nota</h1>

<%= render 'form', nota: @nota %>

<%= link_to 'Show', @nota %> |
<%= link_to 'Back', notas_path %>

app/views/notas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notas</h1>

<table>
  <thead>
    <tr>
      <th>Nota</th>
      <th>Aluno</th>
      <th>Professor</th>
      <th>Disciplina</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notas.each do |nota| %>
      <tr>
        <td><%= nota.nota %></td>
        <td><%= nota.aluno.usuario.nome_aluno %></td>
        <td><%= nota.professor.usuario.nome_aluno %></td>
        <td><%= nota.disciplina.nome %></td>
        <td><%= link_to 'Show', nota %></td>
        <td><%= link_to 'Edit', edit_nota_path(nota) %></td>
        <td><%= link_to 'Destroy', nota, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nota', new_nota_path %>

app/views/notas/new.html.erb
<h1>New Nota</h1>

<%= render 'form', nota: @nota %>

<%= link_to 'Back', notas_path %>

app/views/notas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nota:</strong>
  <%= @nota.nota %>
</p>

<p>
  <strong>Aluno:</strong>
  <%= @nota.aluno.usuario.nome_aluno %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @nota.professor.usuario.nome_aluno %>
</p>

<p>
  <strong>Disciplina:</strong>
  <%= @nota.disciplina.nome %>
</p>

<%= link_to 'Edit', edit_nota_path(@nota) %> |
<%= link_to 'Back', notas_path %>