config/routes.rb
Rails.application.routes.draw do



  resources :nota_trab
  resources :presencas
  resources :matriculas

  resources :notas
  resources :professores
  resources :alunos

  resources :trabalhos

  resources :cursos
  resources :aulas

  resources :usuarios

  resources :disciplinas

end

app/models/aluno.rb
class Aluno < ApplicationRecord
  belongs_to :usuario
  validates :usuario, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aula.rb
class Aula < ApplicationRecord
  belongs_to :disciplina

  validates :disciplina, :data, :objetivo, :realizado, presence:true

end

app/models/curso.rb
class Curso < ApplicationRecord

    validates :nome, presence: true

end

app/models/disciplina.rb
class Disciplina < ApplicationRecord
    validates :nome, :carga_horaria, presence:  true
end

app/models/matricula.rb
class Matricula < ApplicationRecord
  belongs_to :usuario
  belongs_to :curso

  
end

app/models/nota.rb
class Nota < ApplicationRecord
  belongs_to :aluno
  belongs_to :professor
  belongs_to :disciplina

 
end

app/models/nota_trab.rb
class NotaTrab < ApplicationRecord
  belongs_to :aluno
  belongs_to :professor
  belongs_to :disciplina
end

app/models/presenca.rb
class Presenca < ApplicationRecord
  belongs_to :curso
  belongs_to :aluno
  belongs_to :professor
end

app/models/professor.rb
class Professor < ApplicationRecord
  belongs_to :usuario
end

app/models/trabalho.rb
class Trabalho < ApplicationRecord
  belongs_to :disciplina
  validates :descricao, :disciplina, :data_de_entrega, presence: true

end

app/models/usuario.rb
class Usuario < ApplicationRecord

    validates :nome_aluno, :documento, :pai, :mae, :endereco, presence: true

end

app/controllers/nota_trab_controller.rb
class NotaTrabController < ApplicationController
  before_action :set_nota_trab, only: [:show, :edit, :update, :destroy]

  # GET /nota_trab
  # GET /nota_trab.json
  def index
    @nota_trab = NotaTrab.all
  end

  # GET /nota_trab/1
  # GET /nota_trab/1.json
  def show
  end

  # GET /nota_trab/new
  def new
    @nota_trab = NotaTrab.new
  end

  # GET /nota_trab/1/edit
  def edit
  end

  # POST /nota_trab
  # POST /nota_trab.json
  def create
    @nota_trab = NotaTrab.new(nota_trab_params)

    respond_to do |format|
      if @nota_trab.save
        format.html { redirect_to @nota_trab, notice: 'Nota trab was successfully created.' }
        format.json { render :show, status: :created, location: @nota_trab }
      else
        format.html { render :new }
        format.json { render json: @nota_trab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nota_trab/1
  # PATCH/PUT /nota_trab/1.json
  def update
    respond_to do |format|
      if @nota_trab.update(nota_trab_params)
        format.html { redirect_to @nota_trab, notice: 'Nota trab was successfully updated.' }
        format.json { render :show, status: :ok, location: @nota_trab }
      else
        format.html { render :edit }
        format.json { render json: @nota_trab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nota_trab/1
  # DELETE /nota_trab/1.json
  def destroy
    @nota_trab.destroy
    respond_to do |format|
      format.html { redirect_to nota_trab_index_url, notice: 'Nota trab was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nota_trab
      @nota_trab = NotaTrab.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nota_trab_params
      params.require(:nota_trab).permit(:nota, :aluno_id, :professor_id, :disciplina_id)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aulas_helper.rb
module AulasHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/matriculas_helper.rb
module MatriculasHelper
end

app/helpers/nota_trab_helper.rb
module NotaTrabHelper
end

app/helpers/notas_helper.rb
module NotasHelper
end

app/helpers/presencas_helper.rb
module PresencasHelper
end

app/helpers/trabalhos_helper.rb
module TrabalhosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/nota_trab/_form.html.erb
<%= form_with(model: nota_trab, local: true) do |form| %>
  <% if nota_trab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nota_trab.errors.count, "error") %> prohibited this nota_trab from being saved:</h2>

      <ul>
      <% nota_trab.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nota %>
    <%= form.text_field :nota %>
  </div>

  <div class="field">
    <%= form.label :aluno_id %>
    <%= form.select(:aluno_id,
                      Aluno.all.collect{|cl|[cl.usuario.nome_aluno, cl.id]}) %>
  </div>

  <div class="field">
  <%= form.label :professor_id %>
  <%= form.select(:professor_id,
  Professor.all.collect{|cl|[cl.usuario.nome_aluno, cl.id]}) %>
</div>

<div class="field">
  <%= form.label :disciplina_id %>
  <%= form.select :disciplina_id,
  Disciplina.all.collect{|cl|[cl.nome, cl.id]} %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nota_trab/edit.html.erb
<h1>Editing Nota Trab</h1>

<%= render 'form', nota_trab: @nota_trab %>

<%= link_to 'Show', @nota_trab %> |
<%= link_to 'Back', nota_trab_index_path %>

app/views/nota_trab/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nota Trab</h1>

<table>
  <thead>
    <tr>
      <th>Nota</th>
      <th>Aluno</th>
      <th>Professor</th>
      <th>Disciplina</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nota_trab.each do |nota_trab| %>
      <tr>
        <td><%= nota_trab.nota %></td>
        <td><%= nota_trab.aluno.usuario.nome_aluno %></td>
        <td><%= nota_trab.professor.usuario.nome_aluno %></td>
        <td><%= nota_trab.disciplina.nome %></td>
        <td><%= link_to 'Show', nota_trab %></td>
        <td><%= link_to 'Edit', edit_nota_trab_path(nota_trab) %></td>
        <td><%= link_to 'Destroy', nota_trab, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nota Trab', new_nota_trab_path %>

app/views/nota_trab/new.html.erb
<h1>New Nota Trab</h1>

<%= render 'form', nota_trab: @nota_trab %>

<%= link_to 'Back', nota_trab_index_path %>

app/views/nota_trab/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nota:</strong>
  <%= @nota_trab.nota %>
</p>

<p>
  <strong>Aluno:</strong>
  <%= @nota_trab.aluno.usuario.nome_aluno %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @nota_trab.professor.usuario.nome_aluno %>
</p>

<p>
  <strong>Disciplina:</strong>
  <%= @nota_trab.disciplina.nome %>
</p>

<%= link_to 'Edit', edit_nota_trab_path(@nota_trab) %> |
<%= link_to 'Back', nota_trab_index_path %>